---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "demoapp.fullname" . }}-demoapp-config
  namespace: default
data:
{{ (.Files.Glob "files/application.properties").AsConfig | indent 2 }}
